### ISSUE TITLE
locate_postion prints to console

### ISSUE THREAD

**Issue by hardingnj** [alimanfoo/anhima#76]
line 266 of loc.py:

print(p, index)

Can we make it optional perhaps?

**Comment by alimanfoo** [comment]
Yes of course, there shouldn't be any bare print statements, that's
probably just some debugging I forgot to clean up. Will fix.

On Wednesday, January 14, 2015, hardingnj <notifications@github.com> wrote:

> line 266 of loc.py:
>
> print(p, index)
>
> Can we make it optional perhaps?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/alimanfoo/anhima/issues/76>.
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Web: http://purl.org/net/aliman
Email: alimanfoo@gmail.com
Tel: +44 (0)1865 287721

**Comment by alimanfoo** [comment]
Fixed in v0.11.
